"""Create content pipeline tables

Revision ID: 005
Revises: 004_create_team_tables.py
Create Date: 2026-01-25 21:05:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite3

# revision identifiers
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create scripts table
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text()),
        sa.Column('target_audience', sa.String(length=100)),
        sa.Column('estimated_duration', sa.Integer()),
        sa.Column('difficulty_level', sa.String(length=20)),
        sa.Column('character_id', sa.Integer()),
        sa.Column('content_type', sa.String(length=50)),
        sa.Column('status', sa.String(length=50)),
        sa.Column('version', sa.Integer()),
        sa.Column('written_by_id', sa.Integer()),
        sa.Column('reviewed_by_id', sa.Integer()),
        sa.Column('approved_by_id', sa.Integer()),
        sa.Column('review_notes', sa.Text()),
        sa.Column('approval_notes', sa.Text()),
        sa.Column('word_count', sa.Integer()),
        sa.Column('reading_time', sa.Integer()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('submitted_for_review', sa.DateTime(timezone=True)),
        sa.Column('approved_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['approved_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['character_id'], ['islamic_characters'], ['id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['written_by_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_character_id'), 'scripts', ['character_id'])
    op.create_index(op.f('ix_scripts_status'), 'scripts', ['status'])
    op.create_index(op.f('ix_scripts_written_by_id'), 'scripts', ['written_by_id'])
    
    # Create illustrations table
    op.create_table('illustrations',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('scene_description', sa.Text()),
        sa.Column('art_style', sa.String(length=50)),
        sa.Column('color_scheme', sa.JSON()),
        sa.Column('sketch_file', sa.String(length=500)),
        sa.Column('final_file', sa.String(length=500)),
        sa.Column('thumbnail', sa.String(length=500)),
        sa.Column('script_id', sa.Integer()),
        sa.Column('scene_number', sa.Integer()),
        sa.Column('illustration_type', sa.String(length=50)),
        sa.Column('status', sa.String(length=50)),
        sa.Column('priority', sa.String(length=20)),
        sa.Column('illustrated_by_id', sa.Integer()),
        sa.Column('reviewed_by_id', sa.Integer()),
        sa.Column('review_notes', sa.Text()),
        sa.Column('revision_count', sa.Integer()),
        sa.Column('dimensions', sa.JSON()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['illustrated_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['scripts'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_illustrations_script_id'), 'illustrations', ['script_id'])
    op.create_index(op.f('ix_illustrations_status'), 'illustrations', ['status'])
    
    # Create voice_recordings table
    op.create_table('voice_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('script_text', sa.Text()),
        sa.Column('voice_style', sa.String(length=50)),
        sa.Column('tone', sa.String(length=50)),
        sa.Column('language', sa.String(length=10)),
        sa.Column('audio_file', sa.String(length=500)),
        sa.Column('waveform_file', sa.String(length=500)),
        sa.Column('transcript', sa.Text()),
        sa.Column('duration', sa.Float()),
        sa.Column('file_size', sa.Integer()),
        sa.Column('sample_rate', sa.Integer()),
        sa.Column('bit_rate', sa.Integer()),
        sa.Column('format', sa.String(length=20)),
        sa.Column('script_id', sa.Integer()),
        sa.Column('scene_number', sa.Integer()),
        sa.Column('status', sa.String(length=50)),
        sa.Column('quality_rating', sa.Integer()),
        sa.Column('voice_artist_id', sa.Integer()),
        sa.Column('sound_engineer_id', sa.Integer()),
        sa.Column('reviewed_by_id', sa.Integer()),
        sa.Column('review_notes', sa.Text()),
        sa.Column('retake_count', sa.Integer()),
        sa.Column('background_noise_level', sa.Float()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('recorded_at', sa.DateTime(timezone=True)),
        sa.Column('mastered_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['scripts'], ['id'], ),
        sa.ForeignKeyConstraint(['sound_engineer_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['voice_artist_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_recordings_script_id'), 'voice_recordings', ['script_id'])
    op.create_index(op.f('ix_voice_recordings_status'), 'voice_recordings', ['status'])
    
    # Create animations table
    op.create_table('animations',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('animation_type', sa.String(length=50)),
        sa.Column('style', sa.String(length=50)),
        sa.Column('animation_file', sa.String(length=500)),
        sa.Column('preview_file', sa.String(length=500)),
        sa.Column('storyboard_file', sa.String(length=500)),
        sa.Column('duration', sa.Float()),
        sa.Column('frame_rate', sa.Integer()),
        sa.Column('resolution', sa.JSON()),
        sa.Column('file_size', sa.Integer()),
        sa.Column('format', sa.String(length=20)),
        sa.Column('script_id', sa.Integer()),
        sa.Column('scene_number', sa.Integer()),
        sa.Column('status', sa.String(length=50)),
        sa.Column('complexity', sa.String(length=20)),
        sa.Column('animator_id', sa.Integer()),
        sa.Column('motion_graphics_artist_id', sa.Integer()),
        sa.Column('reviewed_by_id', sa.Integer()),
        sa.Column('review_notes', sa.Text()),
        sa.Column('revision_count', sa.Integer()),
        sa.Column('rendering_time', sa.Integer()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['animator_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['motion_graphics_artist_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['scripts'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animations_script_id'), 'animations', ['script_id'])
    op.create_index(op.f('ix_animations_status'), 'animations', ['status'])
    
    # Create content_productions table
    op.create_table('content_productions',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('content_type', sa.String(length=50)),
        sa.Column('character_id', sa.Integer()),
        sa.Column('current_stage', sa.String(length=50)),
        sa.Column('overall_status', sa.String(length=50)),
        sa.Column('completion_percentage', sa.Float()),
        sa.Column('start_date', sa.DateTime(timezone=True)),
        sa.Column('target_completion', sa.DateTime(timezone=True)),
        sa.Column('actual_completion', sa.DateTime(timezone=True)),
        sa.Column('project_manager_id', sa.Integer()),
        sa.Column('script_writer_id', sa.Integer()),
        sa.Column('illustrator_id', sa.Integer()),
        sa.Column('voice_artist_id', sa.Integer()),
        sa.Column('animator_id', sa.Integer()),
        sa.Column('script_id', sa.Integer()),
        sa.Column('final_animation_id', sa.Integer()),
        sa.Column('quality_score', sa.Float()),
        sa.Column('audience_rating', sa.Float()),
        sa.Column('expert_review_score', sa.Float()),
        sa.Column('published_at', sa.DateTime(timezone=True)),
        sa.Column('publish_platforms', sa.JSON()),
        sa.Column('view_count', sa.Integer()),
        sa.Column('engagement_metrics', sa.JSON()),
        sa.Column('estimated_budget', sa.Float()),
        sa.Column('actual_cost', sa.Float()),
        sa.Column('resource_allocation', sa.JSON()),
        sa.Column('tags', sa.JSON()),
        sa.Column('target_audience', sa.String(length=100)),
        sa.Column('educational_value', sa.Text()),
        sa.Column('cultural_significance', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.ForeignKeyConstraint(['animator_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['character_id'], ['islamic_characters'], ['id'], ),
        sa.ForeignKeyConstraint(['final_animation_id'], ['animations'], ['id'], ),
        sa.ForeignKeyConstraint(['illustrator_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['project_manager_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['scripts'], ['id'], ),
        sa.ForeignKeyConstraint(['script_writer_id'], ['team_members'], ['id'], ),
        sa.ForeignKeyConstraint(['voice_artist_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_productions_character_id'), 'content_productions', ['character_id'])
    op.create_index(op.f('ix_content_productions_current_stage'), 'content_productions', ['current_stage'])
    op.create_index(op.f('ix_content_productions_overall_status'), 'content_productions', ['overall_status'])
    
    # Create content_templates table
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('template_type', sa.String(length=50)),
        sa.Column('structure', sa.JSON()),
        sa.Column('guidelines', sa.Text()),
        sa.Column('examples', sa.JSON()),
        sa.Column('checklist', sa.JSON()),
        sa.Column('usage_count', sa.Integer()),
        sa.Column('rating', sa.Float()),
        sa.Column('content_type', sa.String(length=50)),
        sa.Column('target_audience', sa.String(length=100)),
        sa.Column('difficulty_level', sa.String(length=20)),
        sa.Column('estimated_duration', sa.Integer()),
        sa.Column('created_by_id', sa.Integer()),
        sa.Column('is_public', sa.Boolean()),
        sa.Column('is_active', sa.Boolean()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.ForeignKeyConstraint(['created_by_id'], ['team_members'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create publishing_platforms table
    op.create_table('publishing_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('platform_type', sa.String(length=50)),
        sa.Column('api_endpoint', sa.String(length=500)),
        sa.Column('api_key', sa.String(length=500)),
        sa.Column('supported_formats', sa.JSON()),
        sa.Column('max_file_size', sa.Integer()),
        sa.Column('resolution_requirements', sa.JSON()),
        sa.Column('auto_publish', sa.Boolean()),
        sa.Column('scheduling_options', sa.JSON()),
        sa.Column('audience_targeting', sa.JSON()),
        sa.Column('analytics_endpoint', sa.String(length=500)),
        sa.Column('metrics_tracked', sa.JSON()),
        sa.Column('is_active', sa.Boolean()),
        sa.Column('last_sync', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create publications table
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('content_production_id', sa.Integer()),
        sa.Column('platform_id', sa.Integer()),
        sa.Column('published_url', sa.String(length=500)),
        sa.Column('publish_date', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(length=50)),
        sa.Column('view_count', sa.Integer()),
        sa.Column('like_count', sa.Integer()),
        sa.Column('share_count', sa.Integer()),
        sa.Column('comment_count', sa.Integer()),
        sa.Column('engagement_rate', sa.Float()),
        sa.Column('revenue_generated', sa.Float()),
        sa.Column('monetization_type', sa.String(length=50)),
        sa.Column('tags', sa.JSON()),
        sa.Column('audience_demographics', sa.JSON()),
        sa.Column('geographic_distribution', sa.JSON()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)'),
        sa.Column('last_analytics_update', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['content_production_id'], ['content_productions'], ['id'], ),
        sa.ForeignKeyConstraint(['platform_id'], ['publishing_platforms'], ['id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_content_production_id'), 'publications', ['content_production_id'])
    op.create_index(op.f('ix_publications_platform_id'), 'publications', ['platform_id'])
    
    # Insert default content templates
    op.execute("""
        INSERT INTO content_templates (name, description, template_type, structure, guidelines, content_type, created_by_id) VALUES
        ('Character Story Template', 'Template for creating Islamic character stories', 'script', 
         '{"sections": ["introduction", "early_life", "major_achievements", "challenges", "legacy", "lessons"]}',
         'Focus on historical accuracy, moral lessons, and inspirational content. Include quotes and timeline events.',
         'character_story', 1),
        ('Historical Event Template', 'Template for documenting historical Islamic events', 'script',
         '{"sections": ["background", "event_details", "key_figures", "impact", "historical_significance"]}',
         'Ensure historical accuracy, include multiple perspectives, and highlight the event''s importance.',
         'historical_event', 1),
        ('Educational Content Template', 'Template for educational Islamic content', 'script',
         '{"sections": ["learning_objectives", "content", "examples", "activities", "assessment"]}',
         'Make content engaging and age-appropriate. Include practical examples and interactive elements.',
         'educational', 1)
    """)
    
    # Insert default publishing platforms
    op.execute("""
        INSERT INTO publishing_platforms (name, platform_type, supported_formats, max_file_size, is_active) VALUES
        ('Website', 'web', '["mp4", "webm", "jpg", "png"]', 500000000, true),
        ('Mobile App', 'mobile', '["mp4", "jpg", "png"]', 200000000, true),
        ('YouTube', 'social_media', '["mp4", "mov"]', 2000000000, true),
        ('Instagram', 'social_media', '["mp4", "jpg"]', 100000000, true),
        ('TikTok', 'social_media', '["mp4"]', 50000000, true)
    """)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('publishing_platforms')
    op.drop_table('content_templates')
    op.drop_table('content_productions')
    op.drop_table('animations')
    op.drop_table('voice_recordings')
    op.drop_table('illustrations')
    op.drop_table('scripts')
